# Generated by Django 5.1.7 on 2025-04-26 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(choices=[('medicina_general', 'Medicina General'), ('odontologia', 'Odontología'), ('pediatria', 'Pediatría'), ('dermatologia', 'Dermatología'), ('ginecologia', 'Ginecología'), ('psicologia', 'Psicología')], max_length=50)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
