# Generated by Django 5.1.7 on 2025-05-01 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_especialidad_citamedica_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citamedica',
            name='especialidad',
            field=models.CharField(choices=[('medicina_general', 'Medicina General'), ('odontologia', 'Odontología'), ('pediatria', 'Pediatría'), ('dermatologia', 'Dermatología'), ('ginecologia', 'Ginecología'), ('psicologia', 'Psicología')], max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='doctores/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='especialidad',
            field=models.CharField(blank=True, choices=[('medicina_general', 'Medicina General'), ('odontologia', 'Odontología'), ('pediatria', 'Pediatría'), ('dermatologia', 'Dermatología'), ('ginecologia', 'Ginecología'), ('psicologia', 'Psicología')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Especialidad',
        ),
    ]
